// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF59a38b1DecodeGithubComKamaiuIbCpGoClientV1WsModel(in *jlexer.Lexer, out *IncomingMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "topic":
			out.Topic = TopicType(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF59a38b1EncodeGithubComKamaiuIbCpGoClientV1WsModel(out *jwriter.Writer, in IncomingMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"topic\":"
		out.RawString(prefix[1:])
		out.String(string(in.Topic))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v IncomingMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF59a38b1EncodeGithubComKamaiuIbCpGoClientV1WsModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v IncomingMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF59a38b1EncodeGithubComKamaiuIbCpGoClientV1WsModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *IncomingMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF59a38b1DecodeGithubComKamaiuIbCpGoClientV1WsModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *IncomingMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF59a38b1DecodeGithubComKamaiuIbCpGoClientV1WsModel(l, v)
}
